row_length: 5 
rows_count: 5 
rows_curve_budget: 0.78539816339 
row_segments: straight,curved 
row_segment_curved_radius_min: 4.0 
row_segment_curved_radius_max: 5.0 
ground_resolution: 0.1 
hole_prob: "0.04,0.03,0.02,0.0,0.0" 
hole_size_max: "8,6,4,0,0"
