# Noetic Ninjemys (May 2020 - May 2025)
name: ros-noetic

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: virtual_maize_field
          target-ros1-distro: noetic
