# Humble Hawksbill (May 2022 - May 2027)
name: ros-humble-ign

on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2-ign
  push:
    branches:
      - ros2-ign

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: virtual_maize_field
          target-ros2-distro: humble