# Iron Irwini (May 2023 - November 2024)
name: ros-iron-test

on:
  workflow_dispatch:
    branches:
      - ros2
      - fix-ci
  pull_request:
    branches:
      - ros2
      - fix-ci
  push:
    branches:
      - ros2
      - fix-ci

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: iron
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: virtual_maize_field
          target-ros2-distro: iron