# Rolling Ridley (June 2020 - )
name: ros-rolling

on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2
  push:
    branches:
      - ros2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: ros-tooling/setup-ros@master
        with:
          required-ros-distributions: rolling
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: virtual_maize_field
          target-ros2-distro: rolling