# Iron Irwini (May 2023 - November 2024)
name: ros-iron-test

on:
  workflow_dispatch:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2
  push:
    branches:
      - ros2

steps:
  - uses: ros-tooling/setup-ros@v0.6
    with:
      required-ros-distributions: iron
  - uses: ros-tooling/action-ros-ci@v0.3
    with:
      package-name: virtual_maize_field
      target-ros2-distro: iron