# Rolling Ridley (June 2020 - )
name: ros

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ichiro-its/ros2-build-and-test-action@main
