name: ros

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - foxy
          - humble
          - rolling
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: ubuntu:focal
            ros_distribution: foxy
            ros_version: 2

          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
            
          # Rolling Ridley (June 2020 - )
          - docker_image: ubuntu:jammy
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: virtual_maize_field
        target-ros2-distro: ${{ matrix.ros_distribution }}
        skip-tests: true 
